# Generated by Django 5.1.2 on 2025-05-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='servicios',
            field=models.ManyToManyField(related_name='trabajadores', to='core.servicio'),
        ),
    ]
