# Generated by Django 5.1.2 on 2025-05-25 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_direccion_usuario_latitud_usuario_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anos_experiencia', models.IntegerField()),
                ('descripcion_breve', models.TextField(blank=True)),
                ('idiomas', models.CharField(blank=True, max_length=200)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='core.trabajador')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='core.profesion')),
            ],
            options={
                'unique_together': {('trabajador', 'profesion')},
            },
        ),
        migrations.AddField(
            model_name='trabajador',
            name='profesiones',
            field=models.ManyToManyField(related_name='trabajadores', through='core.ExperienciaProfesional', to='core.profesion'),
        ),
    ]
