# Generated by Django 5.1.2 on 2025-05-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profesion_experienciaprofesional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='profesiones',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='core.profesion'),
        ),
    ]
