# Generated by Django 5.1.2 on 2025-05-25 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fototrabajador_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion_estimado', models.DurationField(help_text='Formato HH:MM:SS')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='core.servicio')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='core.trabajador')),
            ],
        ),
    ]
