# Generated by Django 5.1.2 on 2025-05-26 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_planservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fototrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.trabajador'),
        ),
        migrations.DeleteModel(
            name='Valoracion',
        ),
    ]
