# Generated by Django 5.1.2 on 2025-05-29 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_fototrabajador_trabajador_delete_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planservicio',
            name='incluye',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.planservicio')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.trabajador')),
            ],
            options={
                'unique_together': {('plan', 'fecha', 'hora_inicio')},
            },
        ),
    ]
