# Generated by Django 5.1.2 on 2025-05-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_solicitud_nombre_solicitud_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
