# Generated by Django 5.2.1 on 2025-06-03 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_solicitud_latitud_solicitud_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='trabajador',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.cliente'),
        ),
    ]
