# Generated by Django 5.2.1 on 2025-06-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_reserva_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
