# Generated by Django 5.2.1 on 2025-07-03 03:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_peticion_chat_peticion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='enviado_en',
        ),
        migrations.AddField(
            model_name='chat',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='enviado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_trabajador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='peticion',
        ),
        migrations.DeleteModel(
            name='Peticion',
        ),
    ]
