# Generated by Django 5.2.1 on 2025-07-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_chat_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], default=1, verbose_name='Día de la semana'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='hora_preferida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora preferida'),
        ),
    ]
