# Generated by Django 5.2.1 on 2025-07-09 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pagoservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoservicio',
            name='trabajador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.trabajador'),
            preserve_default=False,
        ),
    ]
