# Generated by Django 5.2.1 on 2025-07-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_mensaje_leido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
    ]
