# Generated by Django 5.2.1 on 2025-07-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_mensaje_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
