# Generated by Django 5.2.1 on 2025-07-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_pagosolicitud'),
        ('core', '0028_remove_usuario_push_token_notificacion'),
    ]

    operations = [
    ]
