# Generated by Django 5.2.1 on 2025-07-13 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20250710_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='profesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.profesion'),
        ),
    ]
