# Generated by Django 5.2.1 on 2025-07-13 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_servicio_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profesion'),
        ),
    ]
