# Generated by Django 5.2.1 on 2025-07-15 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_usuario_es_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_recibidos', to='core.trabajador'),
        ),
    ]
