# Generated by Django 5.2.1 on 2025-07-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_trabajador_profesion'),
        ('core', '0032_feedback_trabajador'),
    ]

    operations = [
    ]
