name: CI - Django + React Native

on:
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend - Django
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # Ajusta si está en otra carpeta

      - name: Chequeo Django
        run: |
          cd backend  # Ajusta si tu manage.py está en otro lugar
          python manage.py check

  frontend:
    name: Frontend - React Native
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: |
          cd frontend  # Ajusta si tu React Native está en otra carpeta
          npm install

      - name: Verificar build (puedes cambiar a lint o test)
        run: |
          cd frontend
          npm run build || echo "React Native no compila en CI, solo instalamos dependencias"
